### ISSUE TITLE
Cell segmentation in 3-dimensions?

### ISSUE THREAD

**Issue by SachinDavis** [fish-quant/big-fish-examples#5]
Cells at different z-planes whose nuclei overlap in the two-dimensional projection are interpreted as a single cell. Is there any way to do cell segmentation and nucleus mask generation in 3 dimensions to avoid this issue. See the image attached.

<img width="395" alt="Screen Shot 2021-03-26 at 2 58 28 PM" src="https://user-images.githubusercontent.com/44754522/112680422-bb399c00-8e43-11eb-93de-90f9cd7a0a77.png">

**Comment by Henley13** [comment]
Hi @SachinDavis,

I am sorry for this late answer, but if you (or another user) still need a solution, you can use one of our implemented model in `bigfish.segmentation` (since version 0.6.0) or [Cellpose](https://www.cellpose.org/) model! Especially for the 3D segmentation, you should be able to perform it with Cellpose.

Arthur
